### ISSUE TITLE
node-curl fails to install

### ISSUE THREAD

**Issue by weakish** [jiangmiao/node-curl#25]
`npm install node-curl` gives this error:

```
error (sh src/generate_curl_options_list.sh && (node-gyp rebuild || node-waf configure build))
error Exit status 127
```

**Comment by rjcorwin** [comment]
Same here.

```
npm http GET https://registry.npmjs.org/node-curl/0.3.1
npm http 304 https://registry.npmjs.org/node-curl/0.3.1

> node-curl@0.3.1 install /...../node_modules/node-curl
> sh src/generate_curl_options_list.sh && (node-gyp rebuild || node-waf configure build)

extract constants from 
generate src/integer_options.h
cat: : No such file or directory
generate src/string_options.h
cat: : No such file or directory
generate src/integer_infos.h
cat: : No such file or directory
generate src/string_infos.h
cat: : No such file or directory
generate src/double_infos.h
cat: : No such file or directory
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.25"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/...../node_modules/node-curl/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.10.25/node-v0.10.25.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.25/node-v0.10.25.tar.gz
make: Entering directory `/...../node_modules/node-curl/build'
  CXX(target) Release/obj.target/node-curl/src/node-curl.o
In file included from ../src/node-curl.cc:1:0:
../src/node-curl.h:7:23: fatal error: curl/curl.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/node-curl/src/node-curl.o] Error 1
make: Leaving directory `/....../node_modules/node-curl/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/...../node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.2.0-2-amd64
gyp ERR! command "node" "/...../node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /...../node_modules/node-curl
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
sh: 1: node-waf: not found
npm ERR! node-curl@0.3.1 install: `sh src/generate_curl_options_list.sh && (node-gyp rebuild || node-waf configure build)`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the node-curl@0.3.1 install script.
npm ERR! This is most likely a problem with the node-curl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sh src/generate_curl_options_list.sh && (node-gyp rebuild || node-waf configure build)
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-curl
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-2-amd64
npm ERR! command "/..../node/bin/node" "/..../node/bin/npm" "install"
npm ERR! cwd /......
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /srv/......./npm-debug.log
npm ERR! not ok code 0
```

**Comment by ronny332** [comment]
```
../src/node-curl.h:7:23: fatal error: curl/curl.h: No such file or directory
```

your curl dev headers are missing.

**Comment by robatron** [comment]
Same here :(

**Comment by jimmygle** [comment]
Try [this](https://github.com/jiangmiao/node-curl/issues/34#issuecomment-58904571).

**Comment by weakish** [comment]
@jimmygle This works. Thanks.

**Comment by sznowicki** [comment]
I guess it's not only me who's coming to this page from time to time via Google just to click the "this" link to copy apt install command.

For all you, in my situation, here's the command:

```
sudo apt-get install libcurl3-dev
```
