### ISSUE TITLE
Option URL is not supported

### ISSUE THREAD

**Issue by mudaser-caremerge** [jiangmiao/node-curl#28]
whenever i am use any test script from wiki i am getting this error

Error: unsupported option URL
    at Curl.setopt (/Users/SMAK/vagrant/XXXXX/node/public_html/upload/node_modules/node-curl/lib/Curl.js:67:13)
    at Function.curl.setOptions (/Users/SMAK/vagrant/XXXXX/node/public_html/upload/node_modules/node-curl/lib/CurlBuilder.js:140:22)
    at Function.curl.perform (/Users/SMAK/vagrant/XXXXX/node/public_html/upload/node_modules/node-curl/lib/CurlBuilder.js:67:14)
    at curl (/Users/SMAK/vagrant/XXXXX/node/public_html/upload/node_modules/node-curl/lib/CurlBuilder.js:36:29)
    at /Users/SMAK/vagrant/XXXXX/node/public_html/upload/app.js:39:13
    at fn (/Users/SMAK/vagrant/XXXXX/node/public_html/upload/node_modules/async/lib/async.js:582:34)
    at Object._onImmediate (/Users/SMAK/vagrant/XXXXX/node/public_html/upload/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback](timers.js:330:15)

**Comment by edwardhotchkiss** [comment]
ping

**Comment by mudaser-caremerge** [comment]
pong

**Comment by joshtronic** [comment]
This may help, I was having issues on Ubuntu 16.04 -- https://github.com/joshtronic/node-curl -- I submitted a PR but since I doubt it will get accepted you may just want to install from source:

`npm install /path/to/joshtronic/node-curl`

Also, was having issues with the OpenSSL version of libcurl4. Ended up swapping for the gnutls version

`sudo apt-get install libcurl4-gnutls-dev`

Hope this helps!!
