### ISSUE TITLE
unable to do curl operation

### ISSUE THREAD

**Issue by aruncumer** [jiangmiao/node-curl#35]
system type : 64-bit operating system, x64-based processor
os : windows 8

-----my script----

var curl = require('curlrequest');

var options = {
    url: 'api.github.com/repos/jiangmiao/node-curl'
  , verbose: true
  , stderr: true
};

curl.request(options, function (err, data) {
     data = JSON.parse(data.toString());
     console.log(data);
});

----------------------------Errror ----------------------------
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by roysG** [comment]
any solution?
