### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by npup** [jiangmiao/node-curl#36]
Plain npm install, then:

$ node node_modules/node-curl/examples/test.js 
[cURL 1] Set default options and reset cURL
[cURL 1] reset
[cURL 1] closed.
[cURL 1] opening.
[cURL 1] opened.
[cURL 1] Set option 'VERBOSE' to '1'
[cURL 1] closed.

/Users/petter/nctest/node_modules/node-curl/lib/Curl.js:66
      throw new Error("unsupported option " + option);
            ^
Error: unsupported option VERBOSE
    at Curl.setopt (/Users/petter/nctest/node_modules/node-curl/lib/Curl.js:66:13)
    at Function.curl.setOptions (/Users/petter/nctest/node_modules/node-curl/lib/CurlBuilder.js:156:22)
    at Function.curl.perform (/Users/petter/nctest/node_modules/node-curl/lib/CurlBuilder.js:78:14)
    at curl (/Users/petter/nctest/node_modules/node-curl/lib/CurlBuilder.js:47:29)
    at Object.<anonymous> (/Users/petter/nctest/node_modules/node-curl/examples/test.js:28:3)
    at Object.<anonymous> (/Users/petter/nctest/node_modules/node-curl/examples/test.js:52:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
$ 

This I found out after getting no calls of my own working, and decided to look in the examples.

/p

**Comment by jgkingston** [comment]
Same problem here

Mac 10.9.5
node v0.10.33
npm v1.4.28

On npm install I get the following:

sh src/generate_curl_options_list.sh && (node-gyp rebuild || node-waf configure build)

extract constants from
generate src/integer_options.h
cat: : No such file or directory
generate src/string_options.h
cat: : No such file or directory
generate src/integer_infos.h
cat: : No such file or directory
generate src/string_infos.h
cat: : No such file or directory
generate src/double_infos.h
cat: : No such file or directory
  CXX(target) Release/obj.target/node-curl/src/node-curl.o
  SOLINK_MODULE(target) Release/node-curl.node
  SOLINK_MODULE(target) Release/node-curl.node: Finished
node-curl@0.3.3 node_modules/node-curl
