### ISSUE TITLE
Getting segmentation issue

### ISSUE THREAD

**Issue by kalimsayyed** [jiangmiao/node-curl#37]
I am receiving segmentation error on CentOS 6.5 final.

gdb /usr/bin/php core-php-11-0-0-15549-1420697347
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-64.el6_5.2)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/...
Reading symbols from /usr/bin/php...done.
[New Thread 15591]
[New Thread 15565]
[New Thread 15580]
[New Thread 15574]
[New Thread 15592]
[New Thread 15590]
[New Thread 15560]
[New Thread 15562]
[New Thread 15563]
[New Thread 15585]
[New Thread 15595]
[New Thread 15564]
[New Thread 15581]
[New Thread 15566]
[New Thread 15596]
[New Thread 15567]
[New Thread 15594]
[New Thread 15570]
[New Thread 15573]
[New Thread 15597]
[New Thread 15576]
[New Thread 15577]
[New Thread 15583]
[New Thread 15584]
[New Thread 15586]
[New Thread 15587]
[New Thread 15549]
[New Thread 15589]
[New Thread 15579]
[New Thread 15572]
[New Thread 15588]
[New Thread 15582]
[New Thread 15575]
[New Thread 15578]
[New Thread 15568]
[New Thread 15561]
[New Thread 15569]
[New Thread 15571]
[New Thread 15559]
[New Thread 15598]
[New Thread 15593]
Missing separate debuginfo for /usr/lib64/libaspell.so.15
Try: yum --disablerepo='_' --enablerepo='_-debug_' install /usr/lib/debug/.build-id/a9/3583a303b1fbba4bf8da0fd002fbb42f477baa
Missing separate debuginfo for /usr/lib64/libpspell.so.15
Try: yum --disablerepo='_' --enablerepo='_-debug_' install /usr/lib/debug/.build-id/e4/c20cff52b24c75ed7876ae251a05e7bd2226f4
Missing separate debuginfo for /lib64/libidn.so.11
Try: yum --disablerepo='_' --enablerepo='_-debug_' install /usr/lib/debug/.build-id/41/7a6ed67d904cd799091b56bdfada0d594bb094
Missing separate debuginfo for
Try: yum --disablerepo='_' --enablerepo='_-debug_' install /usr/lib/debug/.build-id/1e/0a7d58f454926e2afb4797865d85801ed65ece
Reading symbols from /lib64/libcrypt-2.12.so...Reading symbols from /usr/lib/debug/lib64/libcrypt-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libcrypt-2.12.so
Reading symbols from /lib64/libz.so.1.2.3...Reading symbols from /usr/lib/debug/lib64/libz.so.1.2.3.debug...done.
done.
Loaded symbols for /lib64/libz.so.1.2.3
Reading symbols from /usr/lib64/libaspell.so.15...
warning: the debug information found in "/usr/lib/debug//usr/lib64/libaspell.so.15.1.4.debug" does not match "/usr/lib64/libaspell.so.15" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib64/libaspell.so.15.1.4.debug" does not match "/usr/lib64/libaspell.so.15" (CRC mismatch).

Missing separate debuginfo for /usr/lib64/libaspell.so.15
Try: yum --disablerepo='_' --enablerepo='_-debug*' install /usr/lib/debug/.build-id/a9/3583a303b1fbba4bf8da0fd002fbb42f477baa.debug
(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libaspell.so.15
Reading symbols from /usr/lib64/libpspell.so.15...
warning: the debug information found in "/usr/lib/debug//usr/lib64/libpspell.so.15.1.4.debug" does not match "/usr/lib64/libpspell.so.15" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib64/libpspell.so.15.1.4.debug" does not match "/usr/lib64/libpspell.so.15" (CRC mismatch).

Missing separate debuginfo for /usr/lib64/libpspell.so.15
Try: yum --disablerepo='_' --enablerepo='_-debug*' install /usr/lib/debug/.build-id/e4/c20cff52b24c75ed7876ae251a05e7bd2226f4.debug
(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libpspell.so.15
Reading symbols from /lib64/librt-2.12.so...Reading symbols from /usr/lib/debug/lib64/librt-2.12.so.debug...done.
done.
Loaded symbols for /lib64/librt-2.12.so
Reading symbols from /usr/lib64/libmcrypt.so.4.4.8...Reading symbols from /usr/lib/debug/usr/lib64/libmcrypt.so.4.4.8.debug...done.
done.
Loaded symbols for /usr/lib64/libmcrypt.so.4.4.8
Reading symbols from /usr/lib64/libstdc++.so.6.0.13...Reading symbols from /usr/lib/debug/usr/lib64/libstdc++.so.6.0.13.debug...done.
done.
Loaded symbols for /usr/lib64/libstdc++.so.6.0.13
Reading symbols from /usr/lib64/libfreetype.so.6.3.22...Reading symbols from /usr/lib/debug/usr/lib64/libfreetype.so.6.3.22.debug...done.
done.
Loaded symbols for /usr/lib64/libfreetype.so.6.3.22
Reading symbols from /usr/lib64/libpng12.so.0.49.0...Reading symbols from /usr/lib/debug/usr/lib64/libpng12.so.0.49.0.debug...done.
done.
Loaded symbols for /usr/lib64/libpng12.so.0.49.0
Reading symbols from /usr/lib64/libjpeg.so.62.0.0...Reading symbols from /usr/lib/debug/usr/lib64/libjpeg.so.62.0.0.debug...done.
done.
Loaded symbols for /usr/lib64/libjpeg.so.62.0.0
Reading symbols from /usr/lib64/libcurl.so.4.1.1...Reading symbols from /usr/lib/debug/usr/lib64/libcurl.so.4.1.1.debug...done.
done.
Loaded symbols for /usr/lib64/libcurl.so.4.1.1
Reading symbols from /lib64/libbz2.so.1.0.4...Reading symbols from /usr/lib/debug/lib64/libbz2.so.1.0.4.debug...done.
done.
Loaded symbols for /lib64/libbz2.so.1.0.4
Reading symbols from /lib64/libm-2.12.so...Reading symbols from /usr/lib/debug/lib64/libm-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libm-2.12.so
Reading symbols from /lib64/libdl-2.12.so...Reading symbols from /usr/lib/debug/lib64/libdl-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libdl-2.12.so
Reading symbols from /lib64/libnsl-2.12.so...Reading symbols from /usr/lib/debug/lib64/libnsl-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libnsl-2.12.so
Reading symbols from /usr/lib64/libxml2.so.2.7.6...Reading symbols from /usr/lib/debug/usr/lib64/libxml2.so.2.7.6.debug...done.
done.
Loaded symbols for /usr/lib64/libxml2.so.2.7.6
Reading symbols from /lib64/libgssapi_krb5.so.2.2...Reading symbols from /usr/lib/debug/lib64/libgssapi_krb5.so.2.2.debug...done.
done.
Loaded symbols for /lib64/libgssapi_krb5.so.2.2
Reading symbols from /lib64/libkrb5.so.3.3...Reading symbols from /usr/lib/debug/lib64/libkrb5.so.3.3.debug...done.
done.
Loaded symbols for /lib64/libkrb5.so.3.3
Reading symbols from /lib64/libk5crypto.so.3.1...Reading symbols from /usr/lib/debug/lib64/libk5crypto.so.3.1.debug...done.
done.
Loaded symbols for /lib64/libk5crypto.so.3.1
Reading symbols from /lib64/libcom_err.so.2.1...Reading symbols from /usr/lib/debug/lib64/libcom_err.so.2.1.debug...done.
done.
Loaded symbols for /lib64/libcom_err.so.2.1
Reading symbols from /usr/lib64/libssl.so.1.0.1e...Reading symbols from /usr/lib/debug/usr/lib64/libssl.so.1.0.1e.debug...done.
done.
Loaded symbols for /usr/lib64/libssl.so.1.0.1e
Reading symbols from /usr/lib64/libcrypto.so.1.0.1e...Reading symbols from /usr/lib/debug/usr/lib64/libcrypto.so.1.0.1e.debug...done.
done.
Loaded symbols for /usr/lib64/libcrypto.so.1.0.1e
Reading symbols from /usr/lib64/libicui18n.so.42.1...Reading symbols from /usr/lib/debug/usr/lib64/libicui18n.so.42.1.debug...done.
done.
Loaded symbols for /usr/lib64/libicui18n.so.42.1
Reading symbols from /usr/lib64/libicuuc.so.42.1...Reading symbols from /usr/lib/debug/usr/lib64/libicuuc.so.42.1.debug...done.
done.
Loaded symbols for /usr/lib64/libicuuc.so.42.1
Reading symbols from /usr/lib64/libicudata.so.42.1...Reading symbols from /usr/lib/debug/usr/lib64/libicudata.so.42.1.debug...
warning: "/usr/lib/debug/usr/lib64/libicudata.so.42.1.debug": separate debug info file has no debug info
(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libicudata.so.42.1
Reading symbols from /usr/lib64/libicuio.so.42.1...Reading symbols from /usr/lib/debug/usr/lib64/libicuio.so.42.1.debug...done.
done.
Loaded symbols for /usr/lib64/libicuio.so.42.1
Reading symbols from /lib64/libgcc_s-4.4.7-20120601.so.1...Reading symbols from /usr/lib/debug/lib64/libgcc_s-4.4.7-20120601.so.1.debug...done.
done.
Loaded symbols for /lib64/libgcc_s-4.4.7-20120601.so.1
Reading symbols from /lib64/libpthread-2.12.so...Reading symbols from /usr/lib/debug/lib64/libpthread-2.12.so.debug...done.
[Thread debugging using libthread_db enabled]
done.
Loaded symbols for /lib64/libpthread-2.12.so
Reading symbols from /lib64/libc-2.12.so...Reading symbols from /usr/lib/debug/lib64/libc-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libc-2.12.so
Reading symbols from /lib64/libresolv-2.12.so...Reading symbols from /usr/lib/debug/lib64/libresolv-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libresolv-2.12.so
Reading symbols from /lib64/libfreebl3.so...Reading symbols from /usr/lib/debug/lib64/libfreebl3.so.debug...done.
done.
Loaded symbols for /lib64/libfreebl3.so
Reading symbols from /lib64/ld-2.12.so...Reading symbols from /usr/lib/debug/lib64/ld-2.12.so.debug...done.
done.
Loaded symbols for /lib64/ld-2.12.so
Reading symbols from /lib64/libidn.so.11...
warning: the debug information found in "/usr/lib/debug//lib64/libidn.so.11.6.1.debug" does not match "/lib64/libidn.so.11" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/lib64/libidn.so.11.6.1.debug" does not match "/lib64/libidn.so.11" (CRC mismatch).

Missing separate debuginfo for /lib64/libidn.so.11
Try: yum --disablerepo='_' --enablerepo='_-debug*' install /usr/lib/debug/.build-id/41/7a6ed67d904cd799091b56bdfada0d594bb094.debug
(no debugging symbols found)...done.
Loaded symbols for /lib64/libidn.so.11
Reading symbols from /lib64/libldap-2.4.so.2.5.6...Reading symbols from /usr/lib/debug/lib64/libldap-2.4.so.2.5.6.debug...done.
done.
Loaded symbols for /lib64/libldap-2.4.so.2.5.6
Reading symbols from /usr/lib64/libssl3.so...Reading symbols from /usr/lib/debug/usr/lib64/libssl3.so.debug...done.
done.
Loaded symbols for /usr/lib64/libssl3.so
Reading symbols from /usr/lib64/libsmime3.so...Reading symbols from /usr/lib/debug/usr/lib64/libsmime3.so.debug...done.
done.
Loaded symbols for /usr/lib64/libsmime3.so
Reading symbols from /usr/lib64/libnss3.so...Reading symbols from /usr/lib/debug/usr/lib64/libnss3.so.debug...done.
done.
Loaded symbols for /usr/lib64/libnss3.so
Reading symbols from /usr/lib64/libnssutil3.so...Reading symbols from /usr/lib/debug/usr/lib64/libnssutil3.so.debug...done.
done.
Loaded symbols for /usr/lib64/libnssutil3.so
Reading symbols from /lib64/libplds4.so...Reading symbols from /usr/lib/debug/lib64/libplds4.so.debug...done.
done.
Loaded symbols for /lib64/libplds4.so
Reading symbols from /lib64/libplc4.so...Reading symbols from /usr/lib/debug/lib64/libplc4.so.debug...done.
done.
Loaded symbols for /lib64/libplc4.so
Reading symbols from /lib64/libnspr4.so...Reading symbols from /usr/lib/debug/lib64/libnspr4.so.debug...done.
done.
Loaded symbols for /lib64/libnspr4.so
Reading symbols from /usr/lib64/libssh2.so.1.0.1...Reading symbols from /usr/lib/debug/usr/lib64/libssh2.so.1.0.1.debug...done.
done.
Loaded symbols for /usr/lib64/libssh2.so.1.0.1
Reading symbols from /lib64/libkrb5support.so.0.1...Reading symbols from /usr/lib/debug/lib64/libkrb5support.so.0.1.debug...done.
done.
Loaded symbols for /lib64/libkrb5support.so.0.1
Reading symbols from /lib64/libkeyutils.so.1.3...Reading symbols from /usr/lib/debug/lib64/libkeyutils.so.1.3.debug...done.
done.
Loaded symbols for /lib64/libkeyutils.so.1.3
Reading symbols from /lib64/liblber-2.4.so.2.5.6...Reading symbols from /usr/lib/debug/lib64/liblber-2.4.so.2.5.6.debug...done.
done.
Loaded symbols for /lib64/liblber-2.4.so.2.5.6
Reading symbols from /usr/lib64/libsasl2.so.2.0.23...Reading symbols from /usr/lib/debug/usr/lib64/libsasl2.so.2.0.23.debug...done.
done.
Loaded symbols for /usr/lib64/libsasl2.so.2.0.23
Reading symbols from /lib64/libselinux.so.1...Reading symbols from /usr/lib/debug/lib64/libselinux.so.1.debug...done.
done.
Loaded symbols for /lib64/libselinux.so.1
Reading symbols from /lib64/libnss_files-2.12.so...Reading symbols from /usr/lib/debug/lib64/libnss_files-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libnss_files-2.12.so
Reading symbols from /lib64/libnss_dns-2.12.so...Reading symbols from /usr/lib/debug/lib64/libnss_dns-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libnss_dns-2.12.so
Core was generated by `php -f /home/cask/kr_nopear_walkthrough_without_log.php 10000'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000003b0f82f94d in Curl_llist_remove (list=0x7f6088000078, e=0x7f60884fc8e0, user=0x0) at llist.c:108

108         e->prev->next = e->next;
(gdb)
(gdb) bt
#0  0x0000003b0f82f94d in Curl_llist_remove (list=0x7f6088000078, e=0x7f60884fc8e0, user=0x0) at llist.c:108
#1  0x0000003b0f82f9f7 in Curl_llist_destroy (list=0x7f6088000078, user=0x0) at llist.c:128
#2  0x0000003b0f830062 in Curl_hash_init (h=0x3b0fa534a0, slots=<value optimized out>, hfunc=<value optimized out>, comparator=<value optimized out>, dtor=<value optimized out>)

```
at hash.c:80
```
#3  0x0000003b0f80f562 in Curl_global_host_cache_init () at hostip.c:139
#4  0x0000003b0f82cae3 in curl_easy_perform (curl=0x7f606c5d3b30) at easy.c:529
#5  0x0000000000530d07 in zif_curl_exec (ht=<value optimized out>, return_value=0x7f606c5975e0, return_value_ptr=<value optimized out>, this_ptr=<value optimized out>,

```
return_value_used=<value optimized out>, tsrm_ls=0x7f606c30aa50) at /usr/local/php-5.5.6/ext/curl/interface.c:2941
```
#6  0x00000000008e5412 in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>, tsrm_ls=<value optimized out>) at /usr/local/php-5.5.6/Zend/zend_vm_execute.h:550
#7  0x00000000008d55bb in execute_ex (execute_data=0x7f606c3e82d0, tsrm_ls=0x7f606c30aa50) at /usr/local/php-5.5.6/Zend/zend_vm_execute.h:363
#8  0x00000000008479c9 in zend_call_function (fci=0x7f605f3f0a90, fci_cache=<value optimized out>, tsrm_ls=0x7f606c30aa50) at /usr/local/php-5.5.6/Zend/zend_execute_API.c:939
#9  0x0000000000871291 in zend_call_method (object_pp=0x7f606c4c34d0, obj_ce=<value optimized out>, fn_proxy=0x0, function_name=0xd43a48 "run", function_name_len=<value optimized out>,

```
retval_ptr_ptr=0x7f605f3f0db0, param_count=0, arg1=0x0, arg2=0x0, tsrm_ls=0x7f606c30aa50) at /usr/local/php-5.5.6/Zend/zend_interfaces.c:97
```
#10 0x0000000000695867 in pthreads_routine (arg=0x326c2d0) at /usr/local/php-5.5.6/ext/pthreads/src/object.c:948
#11 0x0000003b060079d1 in start_thread (arg=0x7f605f3f1700) at pthread_create.c:301
#12 0x0000003b058e886d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115

**Comment by JCMais** [comment]
huh, this is not a php extension. lol
