### ISSUE TITLE
node-gyp 

### ISSUE THREAD

**Issue by slim2014** [jiangmiao/node-curl#45]
when I run node-gyp I got this error:

SyntaxError: EOL while scanning string literal

make: **\* [Makefile] Error 1
make: Leaving directory `/home/slim/testa/build'
gyp ERR! build error 
gyp ERR! stack Error:`make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /home/slim/testa
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

**Comment by joshtronic** [comment]
This may help, I was having issues on Ubuntu 16.04 -- https://github.com/joshtronic/node-curl -- I submitted a PR but since I doubt it will get accepted you may just want to install from source:

`npm install /path/to/joshtronic/node-curl`

Also, was having issues with the OpenSSL version of libcurl4. Ended up swapping for the gnutls version

`sudo apt-get install libcurl4-gnutls-dev`

Hope this helps!!
