### ISSUE TITLE
Cannot find module 'node_modules/node-curl/lib/../build/default/node-curl' in nodeJs v0.12*

### ISSUE THREAD

**Issue by 2byte** [jiangmiao/node-curl#47]
Rollback version node v0.10\* is ok.
v 0.12\* an error

```
/mnt/hgfs/Ubuntu/projects.dev/pamani/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
Error: Cannot find module '/mnt/hgfs/Ubuntu/projects.dev/pamani/node_modules/node-curl/lib/../build/default/node-curl'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/mnt/hgfs/Ubuntu/projects.dev/pamani/node_modules/node-curl/lib/Curl.js:10:12)
    at Object.<anonymous> (/mnt/hgfs/Ubuntu/projects.dev/pamani/node_modules/node-curl/lib/Curl.js:174:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by TimothyRoss** [comment]
+1
