### ISSUE TITLE
Cant install 

### ISSUE THREAD

**Issue by BroadEstimate** [jiangmiao/node-curl#50]
Cant install HOmebridge just gettin This error 

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 4.1.7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! curve25519@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the curve25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls curve25519
npm ERR! There is likely additional logging output above.

**Comment by seanwendt** [comment]
+1

**Comment by BroadEstimate** [comment]
Do it like here https://github.com/cflurin/homebridge-shims/wiki/Minimalist-Homebridge-on-a-Raspberry-Pi

This part fixed the Problem for me ! https://github.com/cflurin/homebridge-shims/wiki/Minimalist-Homebridge-on-a-Raspberry-Pi#install-node

**Comment by joshhowen** [comment]
I have the same problem

**Comment by revelt** [comment]
Me too

**Comment by lasertiger** [comment]
To make it you need to install some development headers. On ubuntu try:

sudo apt-get install libcurl4-openssl-dev

**Comment by zirho** [comment]
getting same errors
links above are broken

**Comment by cskonopka** [comment]
+1

**Comment by jlg-rayalab** [comment]
cant install in node ^4

**Comment by joshtronic** [comment]
This may help, I was having issues on Ubuntu 16.04 -- https://github.com/joshtronic/node-curl -- I submitted a PR but since I doubt it will get accepted you may just want to install from source:

`npm install /path/to/joshtronic/node-curl`

Also, was having issues with the OpenSSL version of libcurl4. Ended up swapping for the gnutls version

`sudo apt-get install libcurl4-gnutls-dev`

Hope this helps!!
