### ISSUE TITLE
FreeBSD: 'curl/curl.h' not found, but it exists inside /usr/local/include

### ISSUE THREAD

**Issue by GiovanniMounir** [jiangmiao/node-curl#58]
I'm getting the following output when trying to install node-curl via npm:

```
# npm install node-curl --unsafe-perm=true

> node-curl@0.3.3 install /usr/local/www/apache24/data/scsug.de/httpdocs/scimport/node_modules/node-curl
> sh src/generate_curl_options_list.sh && (node-gyp rebuild || node-waf configure build)

extract constants from /usr/local/include/curl/curl.h
generate src/integer_options.h
generate src/string_options.h
generate src/integer_infos.h
generate src/string_infos.h
generate src/double_infos.h
  CXX(target) Release/obj.target/node-curl/src/node-curl.o
In file included from ../src/node-curl.cc:1:
../src/node-curl.h:7:10: fatal error: 'curl/curl.h' file not found
#include <curl/curl.h>
         ^
1 error generated.
gmake: *** [node-curl.target.mk:111: Release/obj.target/node-curl/src/node-curl.o] Fehler 1
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System FreeBSD 10.3-RELEASE-p17
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/www/../node_modules/node-curl
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```
```
# ls /usr/local/include/curl/curl.h
/usr/local/include/curl/curl.h
```
Am I missing something?

Thank you!

**Comment by GiovanniMounir** [comment]
Fixed by switching to https://github.com/JCMais/node-libcurl (thanks to #52)
